name: roadx
description: Car Pooling Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.1.1
  #  geolocator: ^6.1.8+1
  location: ^3.2.4
  geocoding: ^1.0.5

  sliding_up_panel: ^1.0.2
  shared_preferences: any
  animated_floatactionbuttons: ^0.1.0
#  flutter_plugin_android_lifecycle: ^1.0.11
  google_maps_webservice: ^0.0.18
  carousel_slider: ^3.0.0
  connectivity: 2.0.2

  fluttertoast: ^7.1.6
#  pull_to_refresh: ^1.6.3
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1
  dio: ^3.0.10
  toggle_switch: ^0.1.8
  get_it: ^5.0.6
  socket_io_client: ^0.9.12
#  adhara_socket_io: ^0.4.2+1
  rating_bar: ^0.2.0
  permission_handler: ^5.0.1+1

  geocoder: ^0.2.1
  provider: ^4.3.3
  url_launcher: ^5.7.10
#  custom_splash: ^0.0.2

#  after_layout: ^1.0.7+2
  stream_loader:
  flutter_staggered_grid_view: ^0.3.3
#  christian_picker_image: ^0.1.8
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.0
  social_login_3: ^0.1.2
#  rxdart: ^0.25.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/
    - assets/images/icon_car_top.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf

